on: 
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

name: Build and Release

jobs:
  build:
    name: Build binaries
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            platform: ubuntu-latest
            name: motify
          - target: x86_64-pc-windows-msvc
            platform: windows-latest
            name: motify.exe
          - target: x86_64-apple-darwin
            platform: macos-latest
            name: motify.app
          - target: aarch64-apple-darwin
            platform: macos-latest
            name: motify-silicon.app
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            override: true
            components: rustfmt, clippy
            target: ${{ matrix.target }}
      - name: Build Artifact
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: target/${{ matrix.target }}/release/${{matrix.name}}
  release:
    name: Release binaries on github
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: motify
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: motify.exe
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.PAT_GITHUB }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Release Builds"
          files: |
            motify
            motify.exe
